# Generated by Django 5.0 on 2024-10-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodology', '0020_remove_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_blood_donation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
