# Generated by Django 5.0 on 2024-10-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodology', '0022_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestpost',
            name='No_of_bag',
            field=models.PositiveIntegerField(),
        ),
    ]
