# Generated by Django 5.0 on 2024-10-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodology', '0023_alter_bloodrequestpost_no_of_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
    ]
